[
    { "id": 1, "nombre": "🚗 Toyota Corolla", "descripcion": "Compacto confiable con excelente consumo de combustible.", "categoria": "Sedán" },
    { "id": 2, "nombre": "🚙 Ford Explorer", "descripcion": "Espaciosa con tracción en las cuatro ruedas y capacidad para siete pasajeros.", "categoria": "SUV" },
    { "id": 3, "nombre": "🏎️ Ferrari 488", "descripcion": "De alto rendimiento con un motor V8 turboalimentado.", "categoria": "Deportivo" },
    { "id": 4, "nombre": "🚗 Honda Civic", "descripcion": "Compacto popular, conocido por su durabilidad y eficiencia.", "categoria": "Sedán" },
    { "id": 5, "nombre": "🚐 Mercedes-Benz Sprinter", "descripcion": "Versátil con múltiples configuraciones para carga y pasajeros.", "categoria": "Furgoneta" },
    { "id": 6, "nombre": "🚙 Jeep Wrangler", "descripcion": "Todoterreno con capacidad para manejar terrenos difíciles.", "categoria": "SUV" },
    { "id": 7, "nombre": "🚗 Tesla Model S", "descripcion": "Eléctrico de lujo con alta autonomía y tecnología avanzada.", "categoria": "Eléctrico" },
    { "id": 8, "nombre": "🏎️ Porsche 911", "descripcion": "Icónico con excelente manejo y un motor de seis cilindros.", "categoria": "Deportivo" },
    { "id": 9, "nombre": "🚗 BMW Serie 3", "descripcion": "De lujo con una mezcla de confort y rendimiento dinámico.", "categoria": "Sedán" },
    { "id": 10, "nombre": "🚙 Toyota RAV4", "descripcion": "Compacto con gran espacio de carga y opciones híbridas.", "categoria": "SUV" },
    { "id": 11, "nombre": "🚗 Audi A4", "descripcion": "Premium con un diseño elegante y tecnología avanzada.", "categoria": "Sedán" },
    { "id": 12, "nombre": "🚙 Chevrolet Tahoe", "descripcion": "De gran tamaño, ideal para familias y con capacidad de remolque.", "categoria": "SUV" },
    { "id": 13, "nombre": "🚗 Hyundai Elantra", "descripcion": "Compacto económico con características de seguridad modernas.", "categoria": "Sedán" },
    { "id": 14, "nombre": "🚙 Subaru Outback", "descripcion": "Crossover con tracción total y excelente capacidad todoterreno.", "categoria": "Crossover" },
    { "id": 15, "nombre": "🏎️ Lamborghini Aventador", "descripcion": "Con un motor V12 y diseño aerodinámico.", "categoria": "Deportivo" },
    { "id": 16, "nombre": "🚐 Ford Transit", "descripcion": "Versátil disponible en versiones de carga y pasajeros.", "categoria": "Furgoneta" },
    { "id": 17, "nombre": "🚙 Volvo XC90", "descripcion": "De lujo con un enfoque en seguridad y comodidad.", "categoria": "SUV" },
    { "id": 18, "nombre": "🚗 Kia Optima", "descripcion": "Mediano con un buen equilibrio entre estilo y rendimiento.", "categoria": "Sedán" },
    { "id": 19, "nombre": "🏎️ McLaren 720S", "descripcion": "Con un motor V8 biturbo y un diseño futurista.", "categoria": "Deportivo" },
    { "id": 20, "nombre": "🚙 Nissan X-Trail", "descripcion": "Compacto con opciones de tracción en las cuatro ruedas.", "categoria": "SUV" },
    { "id": 21, "nombre": "🚗 Volkswagen Passat", "descripcion": "Mediano europeo con un diseño sobrio y buena tecnología.", "categoria": "Sedán" },
    { "id": 22, "nombre": "🚙 BMW X5", "descripcion": "De lujo con tracción integral y tecnología avanzada.", "categoria": "SUV" },
    { "id": 23, "nombre": "🚐 Ram ProMaster", "descripcion": "Diseñada para carga pesada y múltiples configuraciones.", "categoria": "Furgoneta" },
    { "id": 24, "nombre": "🚗 Mazda 6", "descripcion": "Mediano con un enfoque en el placer de conducción.", "categoria": "Sedán" },
    { "id": 25, "nombre": "🏎️ Bugatti Chiron", "descripcion": "Exclusivo con un motor W16 y velocidad increíble.", "categoria": "Deportivo" },
    { "id": 26, "nombre": "🚙 Lexus RX", "descripcion": "De lujo con un motor híbrido opcional y diseño sofisticado.", "categoria": "SUV" },
    { "id": 27, "nombre": "🚗 Mercedes-Benz Clase C", "descripcion": "Premium con una combinación de lujo y rendimiento.", "categoria": "Sedán" },
    { "id": 28, "nombre": "🚙 Honda CR-V", "descripcion": "Compacto con gran espacio interior y eficiencia de combustible.", "categoria": "SUV" },
    { "id": 29, "nombre": "🚗 Peugeot 508", "descripcion": "Europeo elegante con un diseño moderno y eficiente.", "categoria": "Sedán" },
    { "id": 30, "nombre": "🏎️ Chevrolet Corvette", "descripcion": "Estadounidense icónico con un motor V8 de alto rendimiento.", "categoria": "Deportivo" },
    { "id": 31, "nombre": "🚙 Range Rover Sport", "descripcion": "De lujo con capacidad todoterreno y acabados refinados.", "categoria": "SUV" },
    { "id": 32, "nombre": "🚗 Nissan Altima", "descripcion": "Mediano con opciones de tracción integral y motor turbo.", "categoria": "Sedán" },
    { "id": 33, "nombre": "🏎️ Aston Martin DB11", "descripcion": "De lujo británico con un diseño refinado y potente motor V12.", "categoria": "Deportivo" },
    { "id": 34, "nombre": "🚐 Nissan NV200", "descripcion": "Compacta ideal para uso urbano y pequeñas empresas.", "categoria": "Furgoneta" },
    { "id": 35, "nombre": "🚙 Toyota Land Cruiser", "descripcion": "Todoterreno de gran tamaño, famosa por su durabilidad.", "categoria": "SUV" },
    { "id": 36, "nombre": "🚗 Alfa Romeo Giulia", "descripcion": "Deportivo italiano con un enfoque en el rendimiento y el diseño.", "categoria": "Sedán" },
    { "id": 37, "nombre": "🏎️ Audi R8", "descripcion": "Con tracción total y motor V10.", "categoria": "Deportivo" },
    { "id": 38, "nombre": "🚙 Mitsubishi Outlander", "descripcion": "Compacto con opciones híbridas y tracción en las cuatro ruedas.", "categoria": "SUV" },
    { "id": 39, "nombre": "🚐 Renault Kangoo", "descripcion": "Pequeña y práctica, ideal para negocios locales.", "categoria": "Furgoneta" },
    { "id": 40, "nombre": "🚗 Lexus ES", "descripcion": "De lujo con un interior cómodo y un motor híbrido opcional.", "categoria": "Sedán" },
    { "id": 41, "nombre": "🏎️ Ford Mustang GT", "descripcion": "Clásico americano con un potente motor V8.", "categoria": "Deportivo" },
    { "id": 42, "nombre": "🚙 Kia Sorento", "descripcion": "Mediano con opciones de asientos para siete y buenas características tecnológicas.", "categoria": "SUV" },
    { "id": 43, "nombre": "🚐 Citroën Berlingo", "descripcion": "Pequeña con capacidad de carga y opciones de transporte de pasajeros.", "categoria": "Furgoneta" },
    { "id": 44, "nombre": "🚗 Infiniti Q50", "descripcion": "De lujo japonés con un enfoque en el rendimiento y la tecnología.", "categoria": "Sedán" },
    { "id": 45, "nombre": "🏎️ Dodge Charger", "descripcion": "Estadounidense con opciones de motor V6 y V8.", "categoria": "Deportivo" },
    { "id": 46, "nombre": "🚙 Hyundai Santa Fe", "descripcion": "Mediano con una excelente relación calidad-precio y opciones híbridas.", "categoria": "SUV" },
    { "id": 47, "nombre": "🚐 Fiat Ducato", "descripcion": "Europea de gran tamaño, ideal para transporte comercial.", "categoria": "Furgoneta" },
    { "id": 48, "nombre": "🚗 Jaguar XF", "descripcion": "Británico de lujo con un diseño atractivo y tecnología avanzada.", "categoria": "Sedán" },
    { "id": 49, "nombre": "🏎️ Nissan GT-R", "descripcion": "Japonés con un motor biturbo y tracción en las cuatro ruedas.", "categoria": "Deportivo" },
    { "id": 50, "nombre": "🚙 Volkswagen Tiguan", "descripcion": "Compacto europeo con un interior espacioso y buen manejo.", "categoria": "SUV" }
]